import _First_Question from './First.vue';
import _Second_Question from './Second.vue';
import _Third_Question_Draft1 from './Third_Draft1.vue';
import _Fourth_Question from './Fourth.vue';
import _Draft2 from './Draft2.vue';
import _Draft3 from './Draft3.vue';
import _Draft_More from './Draft_More.vue';
import _Done from './Done.vue';
export const First_Question = _First_Question;
export const Second_Question = _Second_Question;
export const Third_Question_Draft1 = _Third_Question_Draft1;
export const Fourth_Question = _Fourth_Question;
export const Draft2 = _Draft2;
export const Draft3 = _Draft3;
export const Draft_More = _Draft_More;
export const Done = _Done;
